### ISSUE TITLE
果壳移动网PC模式失效

### ISSUE THREAD

**Issue by chenjun-110** [zhengmingliang/monkeyScripts#4]
## 需要破解阅读全文的网址：
https://m.guokr.com/article/459147/

## 其他问题：
PC模式，按钮消失，全文没出来。
用F12弄成移动模式可以。

**Comment by zhengmingliang** [comment]
> ## 需要破解阅读全文的网址：
> https://m.guokr.com/article/459147/
> 
> ## 其他问题：
> PC模式，按钮消失，全文没出来。
> 用F12弄成移动模式可以。

嗯嗯，你要是PC的话，就不要用它m.guokr.com了呗，PC模式下看移动界面很难受，改成用www.guokr.com 就好了
