### ISSUE TITLE
建议增加百家号自动展开

### ISSUE THREAD

**Issue by iseeyo** [zhengmingliang/monkeyScripts#7]
## 需要破解阅读全文的网址：
https://baijiahao.baidu.com/s?id=1635483846955634990

## 其他问题：
百度搜索结果里有很多百家号的内容，有些内容质量还是很不错的，但是强制跳转安装app让人反感。

**Comment by zhengmingliang** [comment]
ok

> ## 需要破解阅读全文的网址：
> https://baijiahao.baidu.com/s?id=1635483846955634990
> 
> ## 其他问题：
> 百度搜索结果里有很多百家号的内容，有些内容质量还是很不错的，但是强制跳转安装app让人反感。

Ok，五一期间会进行一次大更新

**Comment by zhengmingliang** [comment]
> ## 需要破解阅读全文的网址：
> https://baijiahao.baidu.com/s?id=1635483846955634990
> 
> ## 其他问题：
> 百度搜索结果里有很多百家号的内容，有些内容质量还是很不错的，但是强制跳转安装app让人反感。

已添加百家号处理，请更新到`2.11.0`
