### ISSUE TITLE
此插件会导致百度首页不能搜索

### ISSUE THREAD

**Issue by YuanfengZhang** [zhengmingliang/monkeyScripts#8]
## 其他问题：此插件会导致百度首页不能搜索。
具体：开启此插件后，进入https://www.baidu.com/ ，在输入框中输入检索词后，点击“百度一下”或使用回车键均无反应。

油猴版本：Tampermonkey BETA 4.13.6137
插件版本：2.11.0
Chrome版本：90.0.4430.93（正式版本） （64 位）
遭遇问题的时间：不确定，最近几天才开始出现，似乎经历了一次油猴更新或者插件更新。

期待回复，非常感谢。

**Comment by zhengmingliang** [comment]
> ## 需要破解阅读全文的网址：none
> ## 其他问题：此插件会导致百度首页不能搜索。
> 具体：开启此插件后，进入https://www.baidu.com/ ，在输入框中输入检索词后，点击“百度一下”或使用回车键均无反应。
> 
> 油猴版本：Tampermonkey BETA 4.13.6137
> 插件版本：2.11.0
> Chrome版本：90.0.4430.93（正式版本） （64 位）
> 遭遇问题的时间：不确定，最近几天才开始出现，似乎经历了一次油猴更新或者插件更新。
> 
> 期待回复，非常感谢。

额，抱歉，因为平时一直用谷歌搜索，不怎么有用百度，最近解决一下这个问题
